import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

import styles from "./layout.module.css";
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      style={{ colorScheme: "dark" }}
      suppressHydrationWarning
    >
      <body className={styles.body}>
        <Navbar />

        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}

/*
            <div style={logo}>Home</div>
            <div>Theme Switcher</div>
            <div>Burger menu</div>
            <div></div>
*/

/*
          <div style={{ display: "grid" }}>
            <NavBar />

            <main className={styles.main}>
              <div className={styles["main-content"]}>{children}</div>
            </main>
          </div>
*/
